### ISSUE TITLE
Initial design 

### ISSUE THREAD

**Issue by Tadele01** [joejnke/Deductive_systems#1]
we will have four classes Agent, World, Action and precept

represent variable
repr
#Agent #World
-current_postition -state
-ok +draw_world()
-visited
-stench
-breeze
+change_position(where to go)
+ get_ajacent(current_position)
+perceive(adjacent)
+do_logical_inference(perceived)
+take_action(logical infered)
#Action #Percept
+goto_left() +is_stench(position)
+goto_right() +is_glitter(position)
+goto_up() +is_breeze(position)
+goto_down() +is_bump(position)
+shoot(where to shoot)
+grab_gold()
+climb_out()

=>Agent initialized at position 1, 1 before the agent take action it execute the get_adjacent method and for this method agent passes its current position
=> After agent gets its adjacent it iteratively calls perceive method for each adjacent point and in perceive method all methods in percept class will be executed
eg Vector perceive (adjacent1){
is_stench(adacent1)
...
}
=>then we let the agent do logical inference based on his knowledge about the world and let the agent take the appropriate action

This is the abstract idea I propose

**Comment by Tadele01** [comment]
currently I am working on get_adjacent method which accept 2d vector and for every pair of numbers the method will find their adjacent pair of numbers

**Comment by joejnke** [comment]
Can you list down:
- the purpose of each class
- the attributes and methods for each of the classes
- how each of them will interact to build up the whole project

**Comment by Tadele01** [comment]
I will attach a pdf file that will have the full design and implementation detail tonight, but until then this is the abstract idea,

#Agent  class variables  

         -typedef std::pair<int,int> Coordinate;
        -Coordinate current_postition        - - to represent agent location 
        -enum Percept	{STENCH, BREEZE, BUMP, GLITTER, SCREAM};
        -ok           -->  a vector to store ok coordinates
        -visited     ---> a vector to store visited coordinates
        -stench    ---> a vector to store stench coordinates
        -breeze   --> a vector to store breeze coordinates


#Agent class methods

        +change_position(where to go)   .........accept a coordinate and change agent position to there
        +get_ajacent(current_position)   ---......accept current position and find all adjacent coordinates 
       +perceive(adjacent)                    ------using adjacent returned by get_adjacent method and figured out what is going on in those adjacent coordinates and store the result in a vector

       +do_logical_inference(perceived)   --- using knowledge based technique and perceived things from the perceive method return value we will use this method to do logical inference

       +take_action(logical infered)    --- call the appropriate method from Action class based on the return value of do_logical_inference 

#Action class methods

       +goto_left() 
       +goto_right() 
       +goto_up() 
       +goto_down() 
       +shoot(where to shoot)
       +grab_gold()
       +climb_out()

#precept class methods 

         +is_stench(position)
         +is_glitter(position)
         +is_breeze(position)
         +is_bump(position)

#world class variable 

         -state

#world class method

         +draw_world()

**Comment by joejnke** [comment]
Fine. After that let's review one another's plan and come up with a merged plan.
