### ISSUE TITLE
Room class 

### ISSUE THREAD

**Issue by Tadele01** [joejnke/Deductive_systems#2]
world is the actual game world and room is one grid in this world right? if so what is the relationship between them does room a subclass of world ?  for every game, content in room can be different as mentioned in class we should randomize the place of wumpus, gold and pit if so how do you plan to handle this randomness ?

**Comment by Tadele01** [comment]
is there a difference between room class and world's grid attribute?

**Comment by joejnke** [comment]
```world is the actual game world and room is one grid in this world right?```

- NO it's not. The world has one grid and this grid has 16 ```room``` instances. We said that grid will be implemented as 2D array of 4X4 size. So, it holds total of 16 ```room``` instances.

```for every game, content in room can be different as mentioned in class we should randomize the place of wumpus, gold and pit if so how do you plan to handle this randomness ?```

- The world has ```grid_init()``` method that will initialize the grid by placing the ```wumpus```, ```gold```, ```pit``` and other knowledge into randomly choosen ```room``` instances from the grid.

```is there a difference between room class and world's grid attribute?```

- Yea they are different. ```room``` is a class but ```grid``` is a 2D array of ```room``` object. It is same as we can say 2D array of integers.
