### ISSUE TITLE
Agent class

### ISSUE THREAD

**Issue by Tadele01** [joejnke/Deductive_systems#4]
why do agent have its own version of grid ? 
why do not agent use already created grid in world class?

**Comment by Tadele01** [comment]
what makes you think to use room_id instead of actual coordinate points to implement agents's movements and also to represent a room(grid) in the world ?

**Comment by joejnke** [comment]
```why do agent have its own version of grid ?```

```why do not agent use already created grid in world class?```

*Room: A knowledge container to implement the concept of a single room in a world's grid.
   It will keep record of every knowledge(state) of a room.*

The grid is a set of rooms in the world containing all the information about the world like ```the room where the wumpus is```, ``` the rooms where the pits are found```, ```the room where the gold is``` and othere related knowledge. So this grid has to be maintained only by the world, other wise every thing will be known and the agent doesn't need to be smart. So, the agent needs to find out and deduce the knowledge in this grid and build its own grid. This means the agent will find out ```the room where the wumpus is```, ``` the rooms where the pits are found```, ```the room where the gold is``` and othere related knowledge using its intelligence on the perception history and the model (the model is shared with the agent unlike the grid).

```what makes you think to use room_id instead of actual coordinate points to implement agents's movements and also to represent a room(grid) in the world ?```

ofcourse the room_id is a coordinate point not  a single number.
